### ISSUE TITLE
CR 4: Message Box 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#10]
<< INDIVIDUAL CR >>

Description: Add message box in reservation details page

Reason: It is vital component that required by the customer whenever they want to book a room. Sometimes they want to input additional information or request.

To be approved by PM: Faid Luqman 
To be issued by Developer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR #10 4 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Message box has been implemented
[reserveinfo.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5386995/reserveinfo.zip)

**Comment by faidluqman** [comment]
Great!
