### ISSUE TITLE
CR 5: Payment Method

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#11]
<< INDIVIDUAL CR ISSUED >>

Description: Refine payment method

Reason: The current system does not give customers the option to pay on the website, instead they have to open their bank account and make the payment there. Everything can’t be done at the web at once.

To be approved by: Faid Luqman
To be fixed by: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 5 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Payment has been implemented
[payment.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387009/payment.zip)

**Comment by faidluqman** [comment]
Thanks
