### ISSUE TITLE
CR 6: Website Design 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#12]
<< INDIVIDUAL CR >>

Description: Refine all website design to be minimalist

Reason: The current website looks and feel in term of design is quite outdated, it is 2013 design. Nowadays, website opt for more modern minimalist concept.

To be approved by Project Manager: Faid Luqman 

To be changed by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 6  approved - 15 August 2020

**Comment by syiifahusna** [comment]
I have implemented the approved web design.
[Web Design.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5386979/Web.Design.zip)

**Comment by faidluqman** [comment]
Nice design Syifa, minimalist as expected.
