### ISSUE TITLE
CR 7: Validation for Room Selection 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#13]
<< INDIVIDUAL CR >>

Description: Add validation (confirmation) of room selection is added when reserving a room

Reason: The current system does not ask for validation from customers when reserving a room. .

To be approved by PM: Faid Luqman 

To be added by Developer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 7 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Validation for Room Selection has been implemented
[reserve.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5389864/reserve.zip)
