### ISSUE TITLE
CR 8: Login 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#14]
<< INDIVIDUAL CR ISSUED >>

Description: Add login functionality

Reason: The current system is not equipped with login functionality allowing any random person to make room reservations.

To be approved by Project Manager: Faid Luqman 

To be fixed by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 8 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Login has been implemented
[login.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387019/login.zip)
