### ISSUE TITLE
CR 9: Registration 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#15]
<< INDIVIDUAL CR >>

Description: Add registration (Sign up) functionality

Reason: The current system does not have any feature enabling customers without an account to register and make an account.

To be approved by Project Manager: Faid Luqman

To be added by Developer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 9 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Register has been implemented
[register.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387027/register.zip)
