### ISSUE TITLE
CR 10: Logout 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#16]
<< INDIVIDUAL CR ISSUE >>

Description: Add logout feature

Reason: It is vital component that required by the customer whenever they want to logout from the account. It is basic fundamental of online website especially for eCommerce and hotel.

To be approved by: Faid Luqman

To be fixed by: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 10 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Logout has been implemented into navigation
[logout.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387024/logout.zip)
