### ISSUE TITLE
CR 11: Reservation History

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#17]
<< INDIVIDUAL CR >>

Description: Add reservation history

Reason: Currently customer cannot see their past reservation history which is essential as sometimes customer want to check what kind of room they stay previously.

To be approved by PM: Faid Luqman

To be added by Developer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 11  approved - 15 August 2020

**Comment by syiifahusna** [comment]
Reservation history has been implemented
[reserve_history.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387035/reserve_history.zip)
