### ISSUE TITLE
CR 12: Status Confirmation

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#18]
<< INDIVIDUAL CR >>

Description: Add Status Confirmation for Admin

Reason: This feature is necessary for admin to accommodate the booking status whether it is booking, confirmed, completed, or cancelled.

To be approved by: Faid Luqman

To be changed by: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 12 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Status confirm has been implemented

[admin_reservation.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387080/admin_reservation.zip)
