### ISSUE TITLE
CR 13: Room Cancellation

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#19]
<< INDIVIDUAL CR ISSUED >>

Description: Add Room Cancellation feature

Reason: Before this, the user cannot cancel the room via website and have to manually contact the staff via telephone. This feature ensures more efficiency smoothness for user to cancel their room.

To be approved by Project Manager: Faid Luqman 

To be added by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 13 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Room cancellation has been implemented
[admin_reservation.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387082/admin_reservation.zip)
