### ISSUE TITLE
CR 14: Navigation Bar 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#20]
<< INDIVIDUAL CR >>

Description: Refine Navigation Bar in term of its button

Reason: Before this, the navigation bar does not provide button for login and register. Now it is added to ensure easiness of user in navigating the website.

To be approved by Project Manager: Faid Luqman

To be added by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 14 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Navigation bar has been implemented
[navigation.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387064/navigation.zip)
