### ISSUE TITLE
CR 15: Bank Accounts 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#21]
<< INDIVIDUAL CR ISSUED >>

Description: Add bank accounts for admin

Reason: The current system does not give the admin the option to add, edit and delete bank option.

To be approved by PM: Faid Luqman

To be added by Developer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 15 approved - 15 August 2020

**Comment by syiifahusna** [comment]
Bank Accounts has been implemented
[admin_bank.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387056/admin_bank.zip)
