### ISSUE TITLE
CR 16: Validation 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#22]
<< INDIVIDUAL CR ISSUED >>

Description: Add validation during login and registration

Reason: The current system does not ask for validation from customers during login or registration.

To be approved by Project Manager: Faid Luqman

To be added by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR 16  approved - 15 August 2020

**Comment by syiifahusna** [comment]
Validation has been implemented
[reserve.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5389857/reserve.zip)

**Comment by syiifahusna** [comment]
Validation has been implemented
[validation.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5389874/validation.zip)

**Comment by faidluqman** [comment]
Alright, thanks
