### ISSUE TITLE
Complete CR 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#23]
Listed below is all the change request that must be attended to:

CR 1: Print Button
CR 2: Searching Capability
CR 3: Banking Types
CR 4: Message Box
CR 5: Payment Method
CR 6: Website Design
CR 7: Room Selection Validation
CR 8: Login
CR 9: Registration
CR 10: Logout
CR 11: Reservation History
CR 12: Status Confirmation
CR 13: Room Cancellation
CR 14: Navigation Bar
CR 15: Bank Accounts
CR 16: Validation

Refer to the attached file for more details.
[ChangeRequestForm_Version1_Faid_Syifa_Faizah.pdf](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5254685/ChangeRequestForm_Version1_Faid_Syifa_Faizah.pdf)

**Comment by faidluqman** [comment]
Change Requests are approved on 8 August - 15 August 2020.

**Comment by faidluqman** [comment]
Every CRs have been implemented. I close this
