### ISSUE TITLE
CR 1: Print Button

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#6]
<< INDIVIDUAL CR ISSUE >>

Description: Revamp the print button for reservation as it is not working as expected due to old non-supported coding.
Reason: Since the print button no longer usable, It is important to fix this defect as it affect the functionality and usability of the website.

To be approved by Project Manager: Faid Luqman 
To be fixed by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
A lil touch up here, the title shall be CR1 to simplify instead of Change Request 1. Also, put [Individual CR Issue] at the top.

**Comment by syiifahusna** [comment]
Print button revamp is done
