### ISSUE TITLE
CR 2: Searching Capability 

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#8]
<< INDIVIDUAL CR >>

Description: Add a new functionality which is a searching capabilities for admin to search on reservation details quickly.

Reason: Since there no searching capabilities, It is hard for admin to search for reservation info which can lead to slowness, lack of productivity and inefficiency.

To be approved by Project Manager: Faid Luqman 
To be changed by Software Developer and Designer: Syifa'Ul Husna

**Comment by faidluqman** [comment]
Okay noted

**Comment by syiifahusna** [comment]
Search reservation capability has been implemented into the system
