### ISSUE TITLE
CR 3: Banking Types

### ISSUE THREAD

**Issue by Faizah1998** [faidluqman/EmpireHotel-HelloWorld-#9]
<< INDIVIDUAL CR >>

Description: Add more option for banking type as part of payment transaction.

Reason: Since the banking type is currently limited to just 4 option, for better usability, two more relevant banking type option should be added.

To be approved by: Faid Luqman
To be changed by: Syifa'Ul Husna

**Comment by faidluqman** [comment]
CR #3 Approved - 8 August 2020

**Comment by syiifahusna** [comment]
[Uploading banking_type.zip…]()

**Comment by syiifahusna** [comment]
Banking Types has been implemented
[banking_type.zip](https://github.com/faidluqman/EmpireHotel-HelloWorld-/files/5387099/banking_type.zip)
